//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCarros
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenderCarro
    {
        public string Nombre_Dueño { get; set; }
        public decimal Telefono_Dueño { get; set; }
        public string Estado { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Tipo { get; set; }
        public System.DateTime Año { get; set; }
        public decimal Precio { get; set; }
        public string Transmision { get; set; }
        public decimal Millaje { get; set; }
        public string Tracción { get; set; }
        public string Combustible { get; set; }
        public int Puertas { get; set; }
        public int Pasajeros { get; set; }
        public string Lugar { get; set; }
        public byte[] Imagen_Vehiculo { get; set; }
        public int Carro_Id { get; set; }
    }
}
