//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int Id { get; set; }
        public string Nombre_Producto { get; set; }
        public decimal Precio { get; set; }
        public decimal Cantidad_Disponible { get; set; }
        public int Suplidor_Id { get; set; }
        public string Suplidor { get; set; }
        public int Categoria_Id { get; set; }
        public System.DateTime Fecha_Llegaron { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Suplidores Suplidores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}
