//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaEcommerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suplidores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suplidores()
        {
            this.Productos = new HashSet<Productos>();
        }
    
        public int Id { get; set; }
        public string Nombre_Categoria { get; set; }
        public System.DateTime Fecha_Afiliacion { get; set; }
        public string Marca { get; set; }
        public decimal Telefono { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos> Productos { get; set; }
    }
}
